# Generated by Django 4.2.5 on 2023-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to read blog ....', max_length=255),
        ),
    ]
