# Generated by Django 4.2.5 on 2023-10-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0009_profile_fb_url_profile_git_url_profile_ins_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fb_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='git_url',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ins_url',
            new_name='website_url',
        ),
    ]
