# Generated by Django 4.2.5 on 2023-10-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0010_rename_fb_url_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website_url',
            new_name='instagram_url',
        ),
    ]
