# Generated by Django 4.2.5 on 2023-10-13 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloghome', '0013_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
